kind: pipeline
name: build:debian

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init --recursive
- name: build:debian
  image: plugins/docker
  group: build
  settings:
    repo: jellyfin/jellyfin
    dry_run: true
    dockerfile: Dockerfile.debian_package


---
kind: pipeline
name: build:docker

steps:
- name: submodules
  image: docker:git
  commands:
    - git submodule update --init --recursive
- name: build:docker
  image: plugins/docker
  group: build
  settings:
    repo: jellyfin/jellyfin
    dry_run: true
