name: '$(GITVERSION_SemVer)+$(GITVERSION_ShortSha)'

variables:
- name: TestProjects
  value: "tests/**/*Tests.csproj"
- name: RestoreBuildProjects
  value: "Jellyfin.Server/Jellyfin.Server.csproj"
- name: DotNetSdkVersion
  value: 3.1.100

pr:
  autoCancel: true

trigger:
  batch: true

jobs:
  - job: GitVersion
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UseGitVersion@5
        inputs:
          versionSpec: '5.x'
          includePrerelease: true
      - task: Bash@3
        displayName: "Export GitVersion Variables"
        name: Versions
        inputs:
          targetType: 'inline'
          script: |
            echo "##vso[task.setvariable variable=ProductVersion;isOutput=true;]$(GitVersion.MajorMinorPatch)"
            echo "##vso[task.setvariable variable=InformationalVersion;isOutput=true;]$(GitVersion.InformationalVersion)"

  - template: azure-pipelines-main.yml
    parameters:
      LinuxImage: "ubuntu-latest"
      RestoreBuildProjects: $(RestoreBuildProjects)

  - template: azure-pipelines-test.yml
    parameters:
      ImageNames:
        Linux: "ubuntu-latest"
        Windows: "windows-latest"
        macOS: "macos-latest"

  - template: azure-pipelines-compat.yml
    parameters:
      Packages:
        Naming:
          NugetPackageName: Jellyfin.Naming
          AssemblyFileName: Emby.Naming.dll
        Controller:
          NugetPackageName: Jellyfin.Controller
          AssemblyFileName: MediaBrowser.Controller.dll
        Model:
          NugetPackageName: Jellyfin.Model
          AssemblyFileName: MediaBrowser.Model.dll
        Common:
          NugetPackageName: Jellyfin.Common
          AssemblyFileName: MediaBrowser.Common.dll
      LinuxImage: "ubuntu-latest"
